import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2200);
await fs.mkdir('previews', { recursive: true });
await page.screenshot({ path: 'previews/01-sunny-neighborhood.png' });
console.log(JSON.stringify({ errors, stats: await page.evaluate(() => window.__ride.stats), canvas: await page.locator('canvas').count() }));
await page.locator('.scene-map-buttons [data-value="coast"]').click();
await page.waitForTimeout(800);
await page.screenshot({ path: 'previews/02-coastal-letters.png' });
await page.locator('.scene-map-buttons [data-value="forest"]').click();
await page.waitForTimeout(800);
await page.screenshot({ path: 'previews/03-into-the-woods.png' });
await page.locator('.scene-map-buttons [data-value="town"]').click();
await page.locator('[data-action="start"]').click();
await page.waitForFunction(() => window.__ride.game?.phase === 'playing');
const word = await page.evaluate(() => window.__ride.game.word.text);
await page.locator('#typing-input').pressSequentially(word, { delay: 130 });
await page.screenshot({ path: 'previews/04-riding.png' });
console.log(JSON.stringify({ game: await page.evaluate(() => ({phase: window.__ride.game.phase, word: window.__ride.game.word, distance: window.__ride.game.distance})), errors }));
await browser.close();
